import { GatewayConfig } from '../types/config.js';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export const defaultConfig: GatewayConfig = {
  server: {
    port: 3000,
    host: '0.0.0.0'
  },
  
  providers: [
    // {
    //   name: 'openai',
    //   apiKey: process.env.OPENAI_API_KEY || '',
    //   baseUrl: 'https://api.openai.com/v1',
    //   enabled: !!process.env.OPENAI_API_KEY,
    //   rateLimit: {
    //     requestsPerMinute: 60,
    //     tokensPerMinute: 150000
    //   },
    //   models: ['gpt-4o', 'gpt-4o-mini', 'o1-mini']
    // },
    {
      name: 'anthropic',
      apiKey: process.env.ANTHROPIC_API_KEY || process.env.ANTHROPIC_AUTH_TOKEN || '',
      baseUrl: process.env.ANTHROPIC_BASE_URL || 'https://api.anthropic.com',
      enabled: !!(process.env.ANTHROPIC_API_KEY || process.env.ANTHROPIC_AUTH_TOKEN),
      rateLimit: {
        requestsPerMinute: 50,
        tokensPerMinute: 100000
      },
      models: [
        'claude-3-5-haiku-20241022',
        'claude-3-5-sonnet-20241022',
        'claude-3-7-sonnet-20250219',
        'claude-3-haiku-20240307',
        'claude-3-opus-20240229',
        'claude-haiku-4-5-20251001',
        'claude-opus-4-1-20250805',
        'claude-opus-4-20250514',
        'claude-opus-4-5-20251101',
        'claude-sonnet-4-20250514',
        'claude-sonnet-4-5-20250929'
      ]
    },
    {
      name: 'moonshot',
      apiKey: process.env.MOONSHOT_API_KEY || '',
      baseUrl: 'https://api.moonshot.cn/v1',
      enabled: !!process.env.MOONSHOT_API_KEY,
      models: ['kimi-k2.5', 'moonshot-v1-8k']
    },
    // {
    //   name: 'groq',
    //   apiKey: process.env.GROQ_API_KEY || '',
    //   baseUrl: 'https://api.groq.com/openai/v1',
    //   enabled: !!process.env.GROQ_API_KEY,
    //   models: ['llama-3.1-8b-instant', 'mixtral-8x7b-32768']
    // },
    {
      name: 'siliconflow',
      apiKey: process.env.SILICONFLOW_API_KEY || '',
      baseUrl: 'https://api.siliconflow.cn/v1',
      enabled: !!process.env.SILICONFLOW_API_KEY,
      models: ['Qwen/Qwen2.5-7B-Instruct']
    },
    {
      name: 'aliyun',
      apiKey: process.env.ALIYUN_API_KEY || '',
      baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
      enabled: !!process.env.ALIYUN_API_KEY,
      rateLimit: {
        requestsPerMinute: 60,
        tokensPerMinute: 200000
      },
      models: [
        // 'deepseek-v3.2',
        // 'kimi-k2.5',
        'qwen3-max-preview',
        'qwen3-max-2026-01-23',
        'glm-4.7',
        'qwen3-vl-plus-2025-12-19',
        'qwen-mt-lite',
        'qwen3-vl-flash-2026-01-22',
        'tongyi-xiaomi-analysis-pro',
        'tongyi-xiaomi-analysis-flash',
        'qwen-plus-2025-12-01',
        'qwen-vl-ocr-2025-11-20',
        'qwen-vl-ocr-2025-08-28',
        'qwen2.5-1.5b-instruct',
        'qwen2.5-0.5b-instruct',
        'deepseek-r1-distill-llama-70b',
        'llama-4-maverick-17b-128e-instruct',
        'llama-4-scout-17b-16e-instruct',
        'MiniMax-M2.1',
        'qwen-flash-character'
      ]
    },
    {
      name: 'minimax',
      apiKey: process.env.MINIMAX_API_KEY || '',
      baseUrl: 'https://api.minimaxi.com/v1',
      enabled: !!process.env.MINIMAX_API_KEY,
      models: ['MiniMax-M2.5', 'MiniMax-M2']
    },
    {
      name: 'nvidia',
      apiKey: process.env.NVIDIA_API_KEY || '',
      baseUrl: 'https://integrate.api.nvidia.com/v1',
      enabled: !!process.env.NVIDIA_API_KEY,
      models: [
        'z-ai/glm5',
        'moonshotai/kimi-k2.5',
        '01-ai/yi-large',
        'abacusai/dracarys-llama-3.1-70b-instruct',
        'adept/fuyu-8b',
        'ai21labs/jamba-1.5-large-instruct',
        'ai21labs/jamba-1.5-mini-instruct',
        'aisingapore/sea-lion-7b-instruct',
        'baai/bge-m3',
        'baichuan-inc/baichuan2-13b-chat',
        'bigcode/starcoder2-15b',
        'bigcode/starcoder2-7b',
        'bytedance/seed-oss-36b-instruct',
        'databricks/dbrx-instruct',
        'deepseek-ai/deepseek-coder-6.7b-instruct',
        'deepseek-ai/deepseek-r1-distill-llama-8b',
        'deepseek-ai/deepseek-r1-distill-qwen-14b',
        'deepseek-ai/deepseek-r1-distill-qwen-32b',
        'deepseek-ai/deepseek-r1-distill-qwen-7b',
        'deepseek-ai/deepseek-v3.1',
        'deepseek-ai/deepseek-v3.1-terminus',
        'deepseek-ai/deepseek-v3.2',
        'google/codegemma-1.1-7b',
        'google/codegemma-7b',
        'google/deplot',
        'google/gemma-2-27b-it',
        'google/gemma-2-2b-it',
        'google/gemma-2-9b-it',
        'google/gemma-2b',
        'google/gemma-3-12b-it',
        'google/gemma-3-1b-it',
        'google/gemma-3-27b-it',
        'google/gemma-3-4b-it',
        'google/gemma-3n-e2b-it',
        'google/gemma-3n-e4b-it',
        'google/gemma-7b',
        'google/paligemma',
        'google/recurrentgemma-2b',
        'google/shieldgemma-9b',
        'gotocompany/gemma-2-9b-cpt-sahabatai-instruct',
        'ibm/granite-3.0-3b-a800m-instruct',
        'ibm/granite-3.0-8b-instruct',
        'ibm/granite-3.3-8b-instruct',
        'ibm/granite-34b-code-instruct',
        'ibm/granite-8b-code-instruct',
        'ibm/granite-guardian-3.0-8b',
        'igenius/colosseum_355b_instruct_16k',
        'igenius/italia_10b_instruct_16k',
        'institute-of-science-tokyo/llama-3.1-swallow-70b-instruct-v0.1',
        'institute-of-science-tokyo/llama-3.1-swallow-8b-instruct-v0.1',
        'marin/marin-8b-instruct',
        'mediatek/breeze-7b-instruct',
        'meta/codellama-70b',
        'meta/llama-3.1-405b-instruct',
        'meta/llama-3.1-70b-instruct',
        'meta/llama-3.1-8b-instruct',
        'meta/llama-3.2-11b-vision-instruct',
        'meta/llama-3.2-1b-instruct',
        'meta/llama-3.2-3b-instruct',
        'meta/llama-3.2-90b-vision-instruct',
        'meta/llama-3.3-70b-instruct',
        'meta/llama-4-maverick-17b-128e-instruct',
        'meta/llama-4-scout-17b-16e-instruct',
        'meta/llama-guard-4-12b',
        'meta/llama2-70b',
        'meta/llama3-70b-instruct',
        'meta/llama3-8b-instruct',
        'microsoft/kosmos-2',
        'microsoft/phi-3-medium-128k-instruct',
        'microsoft/phi-3-medium-4k-instruct',
        'microsoft/phi-3-mini-128k-instruct',
        'microsoft/phi-3-mini-4k-instruct',
        'microsoft/phi-3-small-128k-instruct',
        'microsoft/phi-3-small-8k-instruct',
        'microsoft/phi-3-vision-128k-instruct',
        'microsoft/phi-3.5-mini-instruct',
        'microsoft/phi-3.5-moe-instruct',
        'microsoft/phi-3.5-vision-instruct',
        'microsoft/phi-4-mini-flash-reasoning',
        'microsoft/phi-4-mini-instruct',
        'microsoft/phi-4-multimodal-instruct',
        'minimaxai/minimax-m2',
        'minimaxai/minimax-m2.1',
        'mistralai/codestral-22b-instruct-v0.1',
        'mistralai/devstral-2-123b-instruct-2512',
        'mistralai/magistral-small-2506',
        'mistralai/mamba-codestral-7b-v0.1',
        'mistralai/mathstral-7b-v0.1',
        'mistralai/ministral-14b-instruct-2512',
        'mistralai/mistral-7b-instruct-v0.2',
        'mistralai/mistral-7b-instruct-v0.3',
        'mistralai/mistral-large',
        'mistralai/mistral-large-2-instruct',
        'mistralai/mistral-large-3-675b-instruct-2512',
        'mistralai/mistral-medium-3-instruct',
        'mistralai/mistral-nemotron',
        'mistralai/mistral-small-24b-instruct',
        'mistralai/mistral-small-3.1-24b-instruct-2503',
        'mistralai/mixtral-8x22b-instruct-v0.1',
        'mistralai/mixtral-8x22b-v0.1',
        'mistralai/mixtral-8x7b-instruct-v0.1',
        'moonshotai/kimi-k2-instruct',
        'moonshotai/kimi-k2-instruct-0905',
        'moonshotai/kimi-k2-thinking',
        'moonshotai/kimi-k2.5',
        'nv-mistralai/mistral-nemo-12b-instruct',
        'nvidia/cosmos-reason2-8b',
        'nvidia/embed-qa-4',
        'nvidia/llama-3.1-nemoguard-8b-content-safety',
        'nvidia/llama-3.1-nemoguard-8b-topic-control',
        'nvidia/llama-3.1-nemotron-51b-instruct',
        'nvidia/llama-3.1-nemotron-70b-instruct',
        'nvidia/llama-3.1-nemotron-70b-reward',
        'nvidia/llama-3.1-nemotron-nano-4b-v1.1',
        'nvidia/llama-3.1-nemotron-nano-8b-v1',
        'nvidia/llama-3.1-nemotron-nano-vl-8b-v1',
        'nvidia/llama-3.1-nemotron-safety-guard-8b-v3',
        'nvidia/llama-3.1-nemotron-ultra-253b-v1',
        'nvidia/llama-3.2-nemoretriever-1b-vlm-embed-v1',
        'nvidia/llama-3.2-nemoretriever-300m-embed-v1',
        'nvidia/llama-3.2-nemoretriever-300m-embed-v2',
        'nvidia/llama-3.2-nv-embedqa-1b-v1',
        'nvidia/llama-3.2-nv-embedqa-1b-v2',
        'nvidia/llama-3.3-nemotron-super-49b-v1',
        'nvidia/llama-3.3-nemotron-super-49b-v1.5',
        'nvidia/llama-nemotron-embed-vl-1b-v2',
        'nvidia/llama3-chatqa-1.5-70b',
        'nvidia/llama3-chatqa-1.5-8b',
        'nvidia/mistral-nemo-minitron-8b-8k-instruct',
        'nvidia/mistral-nemo-minitron-8b-base',
        'nvidia/nemoretriever-parse',
        'nvidia/nemotron-3-nano-30b-a3b',
        'nvidia/nemotron-4-340b-instruct',
        'nvidia/nemotron-4-340b-reward',
        'nvidia/nemotron-4-mini-hindi-4b-instruct',
        'nvidia/nemotron-content-safety-reasoning-4b',
        'nvidia/nemotron-mini-4b-instruct',
        'nvidia/nemotron-nano-12b-v2-vl',
        'nvidia/nemotron-nano-3-30b-a3b',
        'nvidia/nemotron-parse',
        'nvidia/neva-22b',
        'nvidia/nv-embed-v1',
        'nvidia/nv-embedcode-7b-v1',
        'nvidia/nv-embedqa-e5-v5',
        'nvidia/nv-embedqa-mistral-7b-v2',
        'nvidia/nvclip',
        'nvidia/nvidia-nemotron-nano-9b-v2',
        'nvidia/riva-translate-4b-instruct',
        'nvidia/riva-translate-4b-instruct-v1.1',
        'nvidia/streampetr',
        'nvidia/usdcode-llama-3.1-70b-instruct',
        'nvidia/vila',
        'openai/gpt-oss-120b',
        'openai/gpt-oss-20b',
        'opengpt-x/teuken-7b-instruct-commercial-v0.4',
        'qwen/qwen2-7b-instruct',
        'qwen/qwen2.5-7b-instruct',
        'qwen/qwen2.5-coder-32b-instruct',
        'qwen/qwen2.5-coder-7b-instruct',
        'qwen/qwen3-235b-a22b',
        'qwen/qwen3-coder-480b-a35b-instruct',
        'qwen/qwen3-next-80b-a3b-instruct',
        'qwen/qwen3-next-80b-a3b-thinking',
        'qwen/qwen3.5-397b-a17b',
        'qwen/qwq-32b',
        'rakuten/rakutenai-7b-chat',
        'rakuten/rakutenai-7b-instruct',
        'sarvamai/sarvam-m',
        'snowflake/arctic-embed-l',
        'speakleash/bielik-11b-v2.3-instruct',
        'speakleash/bielik-11b-v2.6-instruct',
        'stepfun-ai/step-3.5-flash',
        'stockmark/stockmark-2-100b-instruct',
        'thudm/chatglm3-6b',
        'tiiuae/falcon3-7b-instruct',
        'tokyotech-llm/llama-3-swallow-70b-instruct-v0.1',
        'upstage/solar-10.7b-instruct',
        'utter-project/eurollm-9b-instruct',
        'writer/palmyra-creative-122b',
        'writer/palmyra-fin-70b-32k',
        'writer/palmyra-med-70b',
        'writer/palmyra-med-70b-32k',
        'yentinglin/llama-3-taiwan-70b-instruct',
        'z-ai/glm4.7',
        'zyphra/zamba2-7b-instruct'
      ]
    },
    {
      name: 'iflow',
      apiKey: process.env.IFLOW_API_KEY || '',
      baseUrl: 'https://apis.iflow.cn/v1',
      enabled: !!process.env.IFLOW_API_KEY,
      models: ['Qwen3-Coder']
    },
    {
      name: 'deepseek',
      apiKey: process.env.DEEPSEEK_API_KEY || '',
      baseUrl: 'https://api.deepseek.com/v1',
      enabled: !!process.env.DEEPSEEK_API_KEY,
      models: ['deepseek-chat', 'deepseek-reasoner']
    },
    {
      name: 'ollama',
      apiKey: 'ollama',
      baseUrl: process.env.OLLAMA_HOST || 'http://localhost:11434/v1',
      enabled: true,
      models: ['qwen2.5:7b']
    }
  ],
  
  models: [
    // 免费模型
    // {
    //   id: 'llama-3.1-8b-instant',
    //   name: 'Llama 3.1 8B (Groq)',
    //   provider: 'groq',
    //   contextWindow: 128000,
    //   costPer1KInput: 0,
    //   costPer1KOutput: 0,
    //   capabilities: ['text', 'code'],
    //   priority: 1,
    //   enabled: true
    // },
    // {
    //   id: 'mixtral-8x7b-32768',
    //   name: 'Mixtral 8x7B (Groq)',
    //   provider: 'groq',
    //   contextWindow: 32768,
    //   costPer1KInput: 0,
    //   costPer1KOutput: 0,
    //   capabilities: ['text', 'code'],
    //   priority: 2,
    //   enabled: true
    // },
    {
      id: 'Qwen/Qwen2.5-7B-Instruct',
      name: 'Qwen2.5 7B (SiliconFlow)',
      provider: 'siliconflow',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'long_context'],
      priority: 1,
      enabled: true
    },
    // 付费模型
    // {
    //   id: 'gpt-4o-mini',
    //   name: 'GPT-4o Mini',
    //   provider: 'openai',
    //   contextWindow: 128000,
    //   costPer1KInput: 0.00015,
    //   costPer1KOutput: 0.0006,
    //   capabilities: ['text', 'image'],
    //   priority: 3,
    //   enabled: true
    // },
    // {
    //   id: 'gpt-4o',
    //   name: 'GPT-4o',
    //   provider: 'openai',
    //   contextWindow: 128000,
    //   costPer1KInput: 0.005,
    //   costPer1KOutput: 0.015,
    //   capabilities: ['text', 'image', 'code'],
    //   priority: 4,
    //   enabled: true
    // },
    // {
    //   id: 'o1-mini',
    //   name: 'o1-mini',
    //   provider: 'openai',
    //   contextWindow: 128000,
    //   costPer1KInput: 0.003,
    //   costPer1KOutput: 0.012,
    //   capabilities: ['text', 'reasoning', 'code'],
    //   priority: 5,
    //   enabled: true
    // },
    {
      id: 'claude-3-5-haiku-20241022',
      name: 'Claude 3.5 Haiku',
      provider: 'anthropic',
      contextWindow: 200000,
      costPer1KInput: 0.001,
      costPer1KOutput: 0.005,
      capabilities: ['text', 'code'],
      priority: 3,
      enabled: true
    },
    {
      id: 'claude-3-5-sonnet-20241022',
      name: 'Claude 3.5 Sonnet',
      provider: 'anthropic',
      contextWindow: 200000,
      costPer1KInput: 0.003,
      costPer1KOutput: 0.015,
      capabilities: ['text', 'image', 'code'],
      priority: 4,
      enabled: true
    },
    {
      id: 'claude-3-7-sonnet-20250219',
      name: 'Claude 3.7 Sonnet',
      provider: 'anthropic',
      contextWindow: 200000,
      costPer1KInput: 0.003,
      costPer1KOutput: 0.015,
      capabilities: ['text', 'image', 'code', 'reasoning'],
      priority: 5,
      enabled: true
    },
    {
      id: 'claude-3-haiku-20240307',
      name: 'Claude 3 Haiku',
      provider: 'anthropic',
      contextWindow: 200000,
      costPer1KInput: 0.00025,
      costPer1KOutput: 0.00125,
      capabilities: ['text', 'code'],
      priority: 3,
      enabled: true
    },
    {
      id: 'claude-3-opus-20240229',
      name: 'Claude 3 Opus',
      provider: 'anthropic',
      contextWindow: 200000,
      costPer1KInput: 0.015,
      costPer1KOutput: 0.075,
      capabilities: ['text', 'image', 'code', 'reasoning'],
      priority: 6,
      enabled: true
    },
    {
      id: 'claude-haiku-4-5-20251001',
      name: 'Claude Haiku 4.5',
      provider: 'anthropic',
      contextWindow: 200000,
      costPer1KInput: 0.001,
      costPer1KOutput: 0.005,
      capabilities: ['text', 'code'],
      priority: 3,
      enabled: true
    },
    {
      id: 'claude-opus-4-1-20250805',
      name: 'Claude Opus 4.1',
      provider: 'anthropic',
      contextWindow: 200000,
      costPer1KInput: 0.015,
      costPer1KOutput: 0.075,
      capabilities: ['text', 'image', 'code', 'reasoning', 'long_context'],
      priority: 7,
      enabled: true
    },
    {
      id: 'claude-opus-4-20250514',
      name: 'Claude Opus 4',
      provider: 'anthropic',
      contextWindow: 200000,
      costPer1KInput: 0.015,
      costPer1KOutput: 0.075,
      capabilities: ['text', 'image', 'code', 'reasoning', 'long_context'],
      priority: 7,
      enabled: true
    },
    {
      id: 'claude-opus-4-5-20251101',
      name: 'Claude Opus 4.5',
      provider: 'anthropic',
      contextWindow: 200000,
      costPer1KInput: 0.015,
      costPer1KOutput: 0.075,
      capabilities: ['text', 'image', 'code', 'reasoning', 'long_context'],
      priority: 8,
      enabled: true
    },
    {
      id: 'claude-sonnet-4-20250514',
      name: 'Claude Sonnet 4',
      provider: 'anthropic',
      contextWindow: 200000,
      costPer1KInput: 0.003,
      costPer1KOutput: 0.015,
      capabilities: ['text', 'code', 'reasoning', 'long_context'],
      priority: 4,
      enabled: true
    },
    {
      id: 'claude-sonnet-4-5-20250929',
      name: 'Claude Sonnet 4.5',
      provider: 'anthropic',
      contextWindow: 200000,
      costPer1KInput: 0.003,
      costPer1KOutput: 0.015,
      capabilities: ['text', 'code', 'reasoning', 'long_context'],
      priority: 5,
      enabled: true
    },
    {
      id: 'kimi-k2.5',
      name: 'Kimi K2.5',
      provider: 'moonshot',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'long_context', 'code', 'reasoning'],
      priority: 1,
      enabled: true
    },
    {
      id: 'moonshot-v1-8k',
      name: 'Moonshot V1 8K',
      provider: 'moonshot',
      contextWindow: 8000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 2,
      enabled: true
    },
    // Aliyun 阿里云百炼模型（免费额度）
    // {
    //   id: 'deepseek-v3.2',
    //   name: 'DeepSeek V3.2 (Aliyun)',
    //   provider: 'aliyun',
    //   contextWindow: 128000,
    //   costPer1KInput: 0,
    //   costPer1KOutput: 0,
    //   capabilities: ['text', 'code', 'reasoning', 'long_context'],
    //   priority: 1,
    //   enabled: true
    // },
    {
      id: 'qwen3-max-preview',
      name: 'Qwen3 Max Preview (Aliyun)',
      provider: 'aliyun',
      contextWindow: 32000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code', 'reasoning'],
      priority: 1,
      enabled: true
    },
    {
      id: 'qwen3-max-2026-01-23',
      name: 'Qwen3 Max (Aliyun)',
      provider: 'aliyun',
      contextWindow: 32000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code', 'reasoning'],
      priority: 1,
      enabled: true
    },
    {
      id: 'glm-4.7',
      name: 'GLM 4.7 (Aliyun)',
      provider: 'aliyun',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code', 'reasoning'],
      priority: 1,
      enabled: true
    },
    {
      id: 'qwen3-vl-plus-2025-12-19',
      name: 'Qwen3 VL Plus (Aliyun)',
      provider: 'aliyun',
      contextWindow: 32000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'image'],
      priority: 1,
      enabled: true
    },
    {
      id: 'qwen-mt-lite',
      name: 'Qwen MT Lite (Aliyun)',
      provider: 'aliyun',
      contextWindow: 8000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text'],
      priority: 2,
      enabled: true
    },
    {
      id: 'qwen3-vl-flash-2026-01-22',
      name: 'Qwen3 VL Flash (Aliyun)',
      provider: 'aliyun',
      contextWindow: 32000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'image'],
      priority: 1,
      enabled: true
    },
    {
      id: 'tongyi-xiaomi-analysis-pro',
      name: 'Tongyi Xiaomi Analysis Pro (Aliyun)',
      provider: 'aliyun',
      contextWindow: 32000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'reasoning'],
      priority: 1,
      enabled: true
    },
    {
      id: 'tongyi-xiaomi-analysis-flash',
      name: 'Tongyi Xiaomi Analysis Flash (Aliyun)',
      provider: 'aliyun',
      contextWindow: 32000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'reasoning'],
      priority: 2,
      enabled: true
    },
    {
      id: 'qwen-plus-2025-12-01',
      name: 'Qwen Plus (Aliyun)',
      provider: 'aliyun',
      contextWindow: 32000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code', 'reasoning'],
      priority: 1,
      enabled: true
    },
    {
      id: 'qwen-vl-ocr-2025-11-20',
      name: 'Qwen VL OCR (Aliyun)',
      provider: 'aliyun',
      contextWindow: 32000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'image'],
      priority: 1,
      enabled: true
    },
    {
      id: 'qwen-vl-ocr-2025-08-28',
      name: 'Qwen VL OCR Legacy (Aliyun)',
      provider: 'aliyun',
      contextWindow: 32000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'image'],
      priority: 2,
      enabled: true
    },
    {
      id: 'qwen2.5-1.5b-instruct',
      name: 'Qwen2.5 1.5B (Aliyun)',
      provider: 'aliyun',
      contextWindow: 32000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text'],
      priority: 3,
      enabled: true
    },
    {
      id: 'qwen2.5-0.5b-instruct',
      name: 'Qwen2.5 0.5B (Aliyun)',
      provider: 'aliyun',
      contextWindow: 32000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text'],
      priority: 3,
      enabled: true
    },
    {
      id: 'deepseek-r1-distill-llama-70b',
      name: 'DeepSeek R1 Distill Llama 70B (Aliyun)',
      provider: 'aliyun',
      contextWindow: 64000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code', 'reasoning'],
      priority: 1,
      enabled: true
    },
    {
      id: 'llama-4-maverick-17b-128e-instruct',
      name: 'Llama 4 Maverick 17B (Aliyun)',
      provider: 'aliyun',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 1,
      enabled: true
    },
    {
      id: 'llama-4-scout-17b-16e-instruct',
      name: 'Llama 4 Scout 17B (Aliyun)',
      provider: 'aliyun',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 1,
      enabled: true
    },
    {
      id: 'MiniMax-M2.1',
      name: 'MiniMax M2.1 (Aliyun)',
      provider: 'aliyun',
      contextWindow: 32000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 1,
      enabled: true
    },
    {
      id: 'qwen-flash-character',
      name: 'Qwen Flash Character (Aliyun)',
      provider: 'aliyun',
      contextWindow: 8000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text'],
      priority: 2,
      enabled: true
    },
    // MiniMax 模型
    {
      id: 'MiniMax-M2.5',
      name: 'MiniMax M2.5',
      provider: 'minimax',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code', 'reasoning'],
      priority: 1,
      enabled: true
    },
    {
      id: 'MiniMax-M2',
      name: 'MiniMax M2',
      provider: 'minimax',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 2,
      enabled: true
    },
    // NVIDIA 模型
    {
      id: 'z-ai/glm5',
      name: 'GLM-5 (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code', 'reasoning'],
      priority: 1,
      enabled: true
    },
    {
      id: 'moonshotai/kimi-k2.5',
      name: 'Kimi K2.5 (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 131072,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code', 'reasoning'],
      priority: 1,
      enabled: true
    },
    {
      id: '01-ai/yi-large',
      name: 'Yi Large (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 32768,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 2,
      enabled: true
    },
    {
      id: 'abacusai/dracarys-llama-3.1-70b-instruct',
      name: 'Dracarys Llama 3.1 70B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 2,
      enabled: true
    },
    {
      id: 'adept/fuyu-8b',
      name: 'Fuyu 8B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 16384,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'image'],
      priority: 3,
      enabled: true
    },
    {
      id: 'ai21labs/jamba-1.5-large-instruct',
      name: 'Jamba 1.5 Large (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 256000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code', 'long_context'],
      priority: 2,
      enabled: true
    },
    {
      id: 'ai21labs/jamba-1.5-mini-instruct',
      name: 'Jamba 1.5 Mini (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 256000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code', 'long_context'],
      priority: 3,
      enabled: true
    },
    {
      id: 'aisingapore/sea-lion-7b-instruct',
      name: 'SEA-LION 7B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 8192,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 3,
      enabled: true
    },
    {
      id: 'baai/bge-m3',
      name: 'BGE-M3 (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 8192,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text'],
      priority: 3,
      enabled: true
    },
    {
      id: 'baichuan-inc/baichuan2-13b-chat',
      name: 'Baichuan2 13B Chat (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 4096,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 3,
      enabled: true
    },
    {
      id: 'bigcode/starcoder2-15b',
      name: 'StarCoder2 15B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 16384,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['code'],
      priority: 3,
      enabled: true
    },
    {
      id: 'bigcode/starcoder2-7b',
      name: 'StarCoder2 7B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 16384,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['code'],
      priority: 3,
      enabled: true
    },
    {
      id: 'bytedance/seed-oss-36b-instruct',
      name: 'Seed OSS 36B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 2,
      enabled: true
    },
    {
      id: 'databricks/dbrx-instruct',
      name: 'DBRX Instruct (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 32768,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 2,
      enabled: true
    },
    {
      id: 'deepseek-ai/deepseek-coder-6.7b-instruct',
      name: 'DeepSeek Coder 6.7B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 16384,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['code'],
      priority: 3,
      enabled: true
    },
    {
      id: 'deepseek-ai/deepseek-r1-distill-llama-8b',
      name: 'DeepSeek R1 Distill Llama 8B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code', 'reasoning'],
      priority: 2,
      enabled: true
    },
    {
      id: 'deepseek-ai/deepseek-r1-distill-qwen-14b',
      name: 'DeepSeek R1 Distill Qwen 14B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 64000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code', 'reasoning'],
      priority: 2,
      enabled: true
    },
    {
      id: 'deepseek-ai/deepseek-r1-distill-qwen-32b',
      name: 'DeepSeek R1 Distill Qwen 32B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 64000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code', 'reasoning'],
      priority: 2,
      enabled: true
    },
    {
      id: 'deepseek-ai/deepseek-r1-distill-qwen-7b',
      name: 'DeepSeek R1 Distill Qwen 7B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 64000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code', 'reasoning'],
      priority: 3,
      enabled: true
    },
    {
      id: 'deepseek-ai/deepseek-v3.1',
      name: 'DeepSeek V3.1 (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 1,
      enabled: true
    },
    {
      id: 'deepseek-ai/deepseek-v3.1-terminus',
      name: 'DeepSeek V3.1 Terminus (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 1,
      enabled: true
    },
    {
      id: 'deepseek-ai/deepseek-v3.2',
      name: 'DeepSeek V3.2 (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 1,
      enabled: true
    },
    {
      id: 'google/codegemma-1.1-7b',
      name: 'CodeGemma 1.1 7B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 8192,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['code'],
      priority: 3,
      enabled: true
    },
    {
      id: 'google/codegemma-7b',
      name: 'CodeGemma 7B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 8192,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['code'],
      priority: 3,
      enabled: true
    },
    {
      id: 'google/deplot',
      name: 'DePlot (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 4096,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'image'],
      priority: 3,
      enabled: true
    },
    {
      id: 'google/gemma-2-27b-it',
      name: 'Gemma 2 27B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 8192,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 2,
      enabled: true
    },
    {
      id: 'google/gemma-2-2b-it',
      name: 'Gemma 2 2B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 8192,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text'],
      priority: 3,
      enabled: true
    },
    {
      id: 'google/gemma-2-9b-it',
      name: 'Gemma 2 9B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 8192,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 3,
      enabled: true
    },
    {
      id: 'google/gemma-2b',
      name: 'Gemma 2B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 8192,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text'],
      priority: 3,
      enabled: true
    },
    {
      id: 'google/gemma-3-12b-it',
      name: 'Gemma 3 12B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 2,
      enabled: true
    },
    {
      id: 'google/gemma-3-1b-it',
      name: 'Gemma 3 1B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 32768,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text'],
      priority: 3,
      enabled: true
    },
    {
      id: 'google/gemma-3-27b-it',
      name: 'Gemma 3 27B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 2,
      enabled: true
    },
    {
      id: 'google/gemma-3-4b-it',
      name: 'Gemma 3 4B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 3,
      enabled: true
    },
    {
      id: 'google/gemma-3n-e2b-it',
      name: 'Gemma 3n E2B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 8192,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text'],
      priority: 3,
      enabled: true
    },
    {
      id: 'google/gemma-3n-e4b-it',
      name: 'Gemma 3n E4B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 8192,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text'],
      priority: 3,
      enabled: true
    },
    {
      id: 'google/gemma-7b',
      name: 'Gemma 7B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 8192,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 3,
      enabled: true
    },
    {
      id: 'google/paligemma',
      name: 'PaliGemma (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 4096,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'image'],
      priority: 3,
      enabled: true
    },
    {
      id: 'google/recurrentgemma-2b',
      name: 'RecurrentGemma 2B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 8192,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text'],
      priority: 3,
      enabled: true
    },
    {
      id: 'google/shieldgemma-9b',
      name: 'ShieldGemma 9B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 8192,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text'],
      priority: 3,
      enabled: true
    },
    {
      id: 'gotocompany/gemma-2-9b-cpt-sahabatai-instruct',
      name: 'Gemma 2 9B SahabatAI (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 8192,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 3,
      enabled: true
    },
    {
      id: 'ibm/granite-3.0-3b-a800m-instruct',
      name: 'Granite 3.0 3B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 4096,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 3,
      enabled: true
    },
    {
      id: 'ibm/granite-3.0-8b-instruct',
      name: 'Granite 3.0 8B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 4096,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 3,
      enabled: true
    },
    {
      id: 'ibm/granite-3.3-8b-instruct',
      name: 'Granite 3.3 8B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 3,
      enabled: true
    },
    {
      id: 'ibm/granite-34b-code-instruct',
      name: 'Granite 34B Code (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 8192,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['code'],
      priority: 2,
      enabled: true
    },
    {
      id: 'ibm/granite-8b-code-instruct',
      name: 'Granite 8B Code (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 4096,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['code'],
      priority: 3,
      enabled: true
    },
    {
      id: 'ibm/granite-guardian-3.0-8b',
      name: 'Granite Guardian 3.0 8B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 4096,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text'],
      priority: 3,
      enabled: true
    },
    {
      id: 'igenius/colosseum_355b_instruct_16k',
      name: 'Colosseum 355B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 16384,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 1,
      enabled: true
    },
    {
      id: 'igenius/italia_10b_instruct_16k',
      name: 'Italia 10B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 16384,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text'],
      priority: 3,
      enabled: true
    },
    {
      id: 'institute-of-science-tokyo/llama-3.1-swallow-70b-instruct-v0.1',
      name: 'Llama 3.1 Swallow 70B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 2,
      enabled: true
    },
    {
      id: 'institute-of-science-tokyo/llama-3.1-swallow-8b-instruct-v0.1',
      name: 'Llama 3.1 Swallow 8B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 3,
      enabled: true
    },
    {
      id: 'marin/marin-8b-instruct',
      name: 'Marin 8B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 8192,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 3,
      enabled: true
    },
    {
      id: 'mediatek/breeze-7b-instruct',
      name: 'Breeze 7B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 32768,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 3,
      enabled: true
    },
    {
      id: 'meta/codellama-70b',
      name: 'CodeLlama 70B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 16384,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['code'],
      priority: 2,
      enabled: true
    },
    {
      id: 'meta/llama-3.1-405b-instruct',
      name: 'Llama 3.1 405B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 1,
      enabled: true
    },
    {
      id: 'meta/llama-3.1-70b-instruct',
      name: 'Llama 3.1 70B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 2,
      enabled: true
    },
    {
      id: 'meta/llama-3.1-8b-instruct',
      name: 'Llama 3.1 8B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 3,
      enabled: true
    },
    {
      id: 'meta/llama-3.2-11b-vision-instruct',
      name: 'Llama 3.2 11B Vision (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'image'],
      priority: 2,
      enabled: true
    },
    {
      id: 'meta/llama-3.2-1b-instruct',
      name: 'Llama 3.2 1B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text'],
      priority: 3,
      enabled: true
    },
    {
      id: 'meta/llama-3.2-3b-instruct',
      name: 'Llama 3.2 3B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text'],
      priority: 3,
      enabled: true
    },
    {
      id: 'meta/llama-3.2-90b-vision-instruct',
      name: 'Llama 3.2 90B Vision (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'image', 'code'],
      priority: 1,
      enabled: true
    },
    {
      id: 'meta/llama-3.3-70b-instruct',
      name: 'Llama 3.3 70B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 2,
      enabled: true
    },
    {
      id: 'meta/llama-4-maverick-17b-128e-instruct',
      name: 'Llama 4 Maverick 17B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 2,
      enabled: true
    },
    {
      id: 'meta/llama-4-scout-17b-16e-instruct',
      name: 'Llama 4 Scout 17B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 2,
      enabled: true
    },
    {
      id: 'meta/llama-guard-4-12b',
      name: 'Llama Guard 4 12B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text'],
      priority: 3,
      enabled: true
    },
    {
      id: 'meta/llama2-70b',
      name: 'Llama 2 70B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 4096,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 3,
      enabled: true
    },
    {
      id: 'meta/llama3-70b-instruct',
      name: 'Llama 3 70B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 8192,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 2,
      enabled: true
    },
    {
      id: 'meta/llama3-8b-instruct',
      name: 'Llama 3 8B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 8192,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 3,
      enabled: true
    },
    {
      id: 'microsoft/kosmos-2',
      name: 'Kosmos-2 (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 4096,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'image'],
      priority: 3,
      enabled: true
    },
    {
      id: 'microsoft/phi-3-medium-128k-instruct',
      name: 'Phi-3 Medium 128K (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 3,
      enabled: true
    },
    {
      id: 'microsoft/phi-3-medium-4k-instruct',
      name: 'Phi-3 Medium 4K (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 4096,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 3,
      enabled: true
    },
    {
      id: 'microsoft/phi-3-mini-128k-instruct',
      name: 'Phi-3 Mini 128K (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 3,
      enabled: true
    },
    {
      id: 'microsoft/phi-3-mini-4k-instruct',
      name: 'Phi-3 Mini 4K (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 4096,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 3,
      enabled: true
    },
    {
      id: 'microsoft/phi-3-small-128k-instruct',
      name: 'Phi-3 Small 128K (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 3,
      enabled: true
    },
    {
      id: 'microsoft/phi-3-small-8k-instruct',
      name: 'Phi-3 Small 8K (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 8192,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 3,
      enabled: true
    },
    {
      id: 'microsoft/phi-3-vision-128k-instruct',
      name: 'Phi-3 Vision 128K (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'image', 'code'],
      priority: 3,
      enabled: true
    },
    {
      id: 'microsoft/phi-3.5-mini-instruct',
      name: 'Phi-3.5 Mini (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 3,
      enabled: true
    },
    {
      id: 'microsoft/phi-3.5-moe-instruct',
      name: 'Phi-3.5 MoE (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 2,
      enabled: true
    },
    {
      id: 'microsoft/phi-3.5-vision-instruct',
      name: 'Phi-3.5 Vision (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'image', 'code'],
      priority: 3,
      enabled: true
    },
    {
      id: 'microsoft/phi-4-mini-flash-reasoning',
      name: 'Phi-4 Mini Flash Reasoning (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code', 'reasoning'],
      priority: 2,
      enabled: true
    },
    {
      id: 'microsoft/phi-4-mini-instruct',
      name: 'Phi-4 Mini (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 3,
      enabled: true
    },
    {
      id: 'microsoft/phi-4-multimodal-instruct',
      name: 'Phi-4 Multimodal (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'image', 'code'],
      priority: 2,
      enabled: true
    },
    {
      id: 'minimaxai/minimax-m2',
      name: 'MiniMax M2 (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 2,
      enabled: true
    },
    {
      id: 'minimaxai/minimax-m2.1',
      name: 'MiniMax M2.1 (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 2,
      enabled: true
    },
    {
      id: 'mistralai/codestral-22b-instruct-v0.1',
      name: 'Codestral 22B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 32768,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['code'],
      priority: 2,
      enabled: true
    },
    {
      id: 'mistralai/devstral-2-123b-instruct-2512',
      name: 'Devstral 2 123B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['code'],
      priority: 1,
      enabled: true
    },
    {
      id: 'mistralai/magistral-small-2506',
      name: 'Magistral Small (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 32768,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 3,
      enabled: true
    },
    {
      id: 'mistralai/mamba-codestral-7b-v0.1',
      name: 'Mamba Codestral 7B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 16384,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['code'],
      priority: 3,
      enabled: true
    },
    {
      id: 'mistralai/mathstral-7b-v0.1',
      name: 'Mathstral 7B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 32768,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'reasoning'],
      priority: 3,
      enabled: true
    },
    {
      id: 'mistralai/ministral-14b-instruct-2512',
      name: 'Ministral 14B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 2,
      enabled: true
    },
    {
      id: 'mistralai/mistral-7b-instruct-v0.2',
      name: 'Mistral 7B v0.2 (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 32768,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 3,
      enabled: true
    },
    {
      id: 'mistralai/mistral-7b-instruct-v0.3',
      name: 'Mistral 7B v0.3 (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 32768,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 3,
      enabled: true
    },
    {
      id: 'mistralai/mistral-large',
      name: 'Mistral Large (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 32768,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 2,
      enabled: true
    },
    {
      id: 'mistralai/mistral-large-2-instruct',
      name: 'Mistral Large 2 (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 1,
      enabled: true
    },
    {
      id: 'mistralai/mistral-large-3-675b-instruct-2512',
      name: 'Mistral Large 3 675B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 1,
      enabled: true
    },
    {
      id: 'mistralai/mistral-medium-3-instruct',
      name: 'Mistral Medium 3 (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 2,
      enabled: true
    },
    {
      id: 'mistralai/mistral-nemotron',
      name: 'Mistral Nemotron (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 2,
      enabled: true
    },
    {
      id: 'mistralai/mistral-small-24b-instruct',
      name: 'Mistral Small 24B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 32768,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 2,
      enabled: true
    },
    {
      id: 'mistralai/mistral-small-3.1-24b-instruct-2503',
      name: 'Mistral Small 3.1 24B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 2,
      enabled: true
    },
    {
      id: 'mistralai/mixtral-8x22b-instruct-v0.1',
      name: 'Mixtral 8x22B Instruct (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 65536,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 2,
      enabled: true
    },
    {
      id: 'mistralai/mixtral-8x22b-v0.1',
      name: 'Mixtral 8x22B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 65536,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 2,
      enabled: true
    },
    {
      id: 'mistralai/mixtral-8x7b-instruct-v0.1',
      name: 'Mixtral 8x7B Instruct (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 32768,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 2,
      enabled: true
    },
    {
      id: 'moonshotai/kimi-k2-instruct',
      name: 'Kimi K2 Instruct (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 131072,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code', 'reasoning'],
      priority: 1,
      enabled: true
    },
    {
      id: 'moonshotai/kimi-k2-instruct-0905',
      name: 'Kimi K2 Instruct 0905 (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 131072,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code', 'reasoning'],
      priority: 1,
      enabled: true
    },
    {
      id: 'moonshotai/kimi-k2-thinking',
      name: 'Kimi K2 Thinking (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 131072,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code', 'reasoning'],
      priority: 1,
      enabled: true
    },
    {
      id: 'moonshotai/kimi-k2.5',
      name: 'Kimi K2.5 v2 (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 131072,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code', 'reasoning'],
      priority: 1,
      enabled: true
    },
    {
      id: 'nv-mistralai/mistral-nemo-12b-instruct',
      name: 'Mistral Nemo 12B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 2,
      enabled: true
    },
    {
      id: 'nvidia/cosmos-reason2-8b',
      name: 'Cosmos Reason2 8B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 8192,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'reasoning'],
      priority: 3,
      enabled: true
    },
    {
      id: 'nvidia/embed-qa-4',
      name: 'Embed QA 4 (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 512,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text'],
      priority: 3,
      enabled: true
    },
    {
      id: 'nvidia/llama-3.1-nemoguard-8b-content-safety',
      name: 'NemoGuard 8B Content Safety (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text'],
      priority: 3,
      enabled: true
    },
    {
      id: 'nvidia/llama-3.1-nemoguard-8b-topic-control',
      name: 'NemoGuard 8B Topic Control (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text'],
      priority: 3,
      enabled: true
    },
    {
      id: 'nvidia/llama-3.1-nemotron-51b-instruct',
      name: 'Nemotron 51B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 2,
      enabled: true
    },
    {
      id: 'nvidia/llama-3.1-nemotron-70b-instruct',
      name: 'Nemotron 70B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 1,
      enabled: true
    },
    {
      id: 'nvidia/llama-3.1-nemotron-70b-reward',
      name: 'Nemotron 70B Reward (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text'],
      priority: 3,
      enabled: true
    },
    {
      id: 'nvidia/llama-3.1-nemotron-nano-4b-v1.1',
      name: 'Nemotron Nano 4B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 3,
      enabled: true
    },
    {
      id: 'nvidia/llama-3.1-nemotron-nano-8b-v1',
      name: 'Nemotron Nano 8B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 3,
      enabled: true
    },
    {
      id: 'nvidia/llama-3.1-nemotron-nano-vl-8b-v1',
      name: 'Nemotron Nano VL 8B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'image'],
      priority: 3,
      enabled: true
    },
    {
      id: 'nvidia/llama-3.1-nemotron-safety-guard-8b-v3',
      name: 'Nemotron Safety Guard 8B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text'],
      priority: 3,
      enabled: true
    },
    {
      id: 'nvidia/llama-3.1-nemotron-ultra-253b-v1',
      name: 'Nemotron Ultra 253B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code', 'reasoning'],
      priority: 1,
      enabled: true
    },
    {
      id: 'nvidia/llama-3.2-nemoretriever-1b-vlm-embed-v1',
      name: 'NemoRetriever 1B VLM (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 4096,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'image'],
      priority: 3,
      enabled: true
    },
    {
      id: 'nvidia/llama-3.2-nemoretriever-300m-embed-v1',
      name: 'NemoRetriever 300M Embed v1 (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 512,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text'],
      priority: 3,
      enabled: true
    },
    {
      id: 'nvidia/llama-3.2-nemoretriever-300m-embed-v2',
      name: 'NemoRetriever 300M Embed v2 (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 512,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text'],
      priority: 3,
      enabled: true
    },
    {
      id: 'nvidia/llama-3.2-nv-embedqa-1b-v1',
      name: 'NV EmbedQA 1B v1 (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 512,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text'],
      priority: 3,
      enabled: true
    },
    {
      id: 'nvidia/llama-3.2-nv-embedqa-1b-v2',
      name: 'NV EmbedQA 1B v2 (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 512,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text'],
      priority: 3,
      enabled: true
    },
    {
      id: 'nvidia/llama-3.3-nemotron-super-49b-v1',
      name: 'Nemotron Super 49B v1 (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 2,
      enabled: true
    },
    {
      id: 'nvidia/llama-3.3-nemotron-super-49b-v1.5',
      name: 'Nemotron Super 49B v1.5 (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 2,
      enabled: true
    },
    {
      id: 'nvidia/llama-nemotron-embed-vl-1b-v2',
      name: 'Nemotron Embed VL 1B v2 (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 4096,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'image'],
      priority: 3,
      enabled: true
    },
    {
      id: 'nvidia/llama3-chatqa-1.5-70b',
      name: 'ChatQA 1.5 70B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 32768,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text'],
      priority: 2,
      enabled: true
    },
    {
      id: 'nvidia/llama3-chatqa-1.5-8b',
      name: 'ChatQA 1.5 8B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 32768,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text'],
      priority: 3,
      enabled: true
    },
    {
      id: 'nvidia/mistral-nemo-minitron-8b-8k-instruct',
      name: 'Mistral Nemo Minitron 8B 8K (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 8192,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 3,
      enabled: true
    },
    {
      id: 'nvidia/mistral-nemo-minitron-8b-base',
      name: 'Mistral Nemo Minitron 8B Base (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 8192,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 3,
      enabled: true
    },
    {
      id: 'nvidia/nemoretriever-parse',
      name: 'NemoRetriever Parse (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 4096,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text'],
      priority: 3,
      enabled: true
    },
    {
      id: 'nvidia/nemotron-3-nano-30b-a3b',
      name: 'Nemotron 3 Nano 30B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 4096,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 2,
      enabled: true
    },
    {
      id: 'nvidia/nemotron-4-340b-instruct',
      name: 'Nemotron 4 340B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 4096,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 1,
      enabled: true
    },
    {
      id: 'nvidia/nemotron-4-340b-reward',
      name: 'Nemotron 4 340B Reward (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 4096,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text'],
      priority: 3,
      enabled: true
    },
    {
      id: 'nvidia/nemotron-4-mini-hindi-4b-instruct',
      name: 'Nemotron 4 Mini Hindi 4B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 4096,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text'],
      priority: 3,
      enabled: true
    },
    {
      id: 'nvidia/nemotron-content-safety-reasoning-4b',
      name: 'Nemotron Content Safety Reasoning 4B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 4096,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text'],
      priority: 3,
      enabled: true
    },
    {
      id: 'nvidia/nemotron-mini-4b-instruct',
      name: 'Nemotron Mini 4B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 4096,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 3,
      enabled: true
    },
    {
      id: 'nvidia/nemotron-nano-12b-v2-vl',
      name: 'Nemotron Nano 12B VL (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'image'],
      priority: 2,
      enabled: true
    },
    {
      id: 'nvidia/nemotron-nano-3-30b-a3b',
      name: 'Nemotron Nano 3 30B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 2,
      enabled: true
    },
    {
      id: 'nvidia/nemotron-parse',
      name: 'Nemotron Parse (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 4096,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text'],
      priority: 3,
      enabled: true
    },
    {
      id: 'nvidia/neva-22b',
      name: 'NeVA 22B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 4096,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'image'],
      priority: 3,
      enabled: true
    },
    {
      id: 'nvidia/nv-embed-v1',
      name: 'NV Embed v1 (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 512,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text'],
      priority: 3,
      enabled: true
    },
    {
      id: 'nvidia/nv-embedcode-7b-v1',
      name: 'NV EmbedCode 7B v1 (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 512,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['code'],
      priority: 3,
      enabled: true
    },
    {
      id: 'nvidia/nv-embedqa-e5-v5',
      name: 'NV EmbedQA E5 v5 (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 512,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text'],
      priority: 3,
      enabled: true
    },
    {
      id: 'nvidia/nv-embedqa-mistral-7b-v2',
      name: 'NV EmbedQA Mistral 7B v2 (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 512,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text'],
      priority: 3,
      enabled: true
    },
    {
      id: 'nvidia/nvclip',
      name: 'NVCLIP (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 512,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'image'],
      priority: 3,
      enabled: true
    },
    {
      id: 'nvidia/nvidia-nemotron-nano-9b-v2',
      name: 'Nemotron Nano 9B v2 (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 3,
      enabled: true
    },
    {
      id: 'nvidia/riva-translate-4b-instruct',
      name: 'Riva Translate 4B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 4096,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text'],
      priority: 3,
      enabled: true
    },
    {
      id: 'nvidia/riva-translate-4b-instruct-v1.1',
      name: 'Riva Translate 4B v1.1 (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 4096,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text'],
      priority: 3,
      enabled: true
    },
    {
      id: 'nvidia/streampetr',
      name: 'StreamPETR (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 4096,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text'],
      priority: 3,
      enabled: true
    },
    {
      id: 'nvidia/usdcode-llama-3.1-70b-instruct',
      name: 'USDCode Llama 3.1 70B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['code'],
      priority: 2,
      enabled: true
    },
    {
      id: 'nvidia/vila',
      name: 'VILA (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 4096,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'image'],
      priority: 3,
      enabled: true
    },
    {
      id: 'openai/gpt-oss-120b',
      name: 'GPT OSS 120B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 1,
      enabled: true
    },
    {
      id: 'openai/gpt-oss-20b',
      name: 'GPT OSS 20B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 2,
      enabled: true
    },
    {
      id: 'opengpt-x/teuken-7b-instruct-commercial-v0.4',
      name: 'Teuken 7B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 8192,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text'],
      priority: 3,
      enabled: true
    },
    {
      id: 'qwen/qwen2-7b-instruct',
      name: 'Qwen2 7B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 3,
      enabled: true
    },
    {
      id: 'qwen/qwen2.5-7b-instruct',
      name: 'Qwen2.5 7B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 3,
      enabled: true
    },
    {
      id: 'qwen/qwen2.5-coder-32b-instruct',
      name: 'Qwen2.5 Coder 32B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['code'],
      priority: 2,
      enabled: true
    },
    {
      id: 'qwen/qwen2.5-coder-7b-instruct',
      name: 'Qwen2.5 Coder 7B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['code'],
      priority: 3,
      enabled: true
    },
    {
      id: 'qwen/qwen3-235b-a22b',
      name: 'Qwen3 235B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code', 'reasoning'],
      priority: 1,
      enabled: true
    },
    {
      id: 'qwen/qwen3-coder-480b-a35b-instruct',
      name: 'Qwen3 Coder 480B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['code'],
      priority: 1,
      enabled: true
    },
    {
      id: 'qwen/qwen3-next-80b-a3b-instruct',
      name: 'Qwen3 Next 80B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 2,
      enabled: true
    },
    {
      id: 'qwen/qwen3-next-80b-a3b-thinking',
      name: 'Qwen3 Next 80B Thinking (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code', 'reasoning'],
      priority: 1,
      enabled: true
    },
    {
      id: 'qwen/qwen3.5-397b-a17b',
      name: 'Qwen3.5 397B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code', 'reasoning'],
      priority: 1,
      enabled: true
    },
    {
      id: 'qwen/qwq-32b',
      name: 'QwQ 32B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code', 'reasoning'],
      priority: 2,
      enabled: true
    },
    {
      id: 'rakuten/rakutenai-7b-chat',
      name: 'RakutenAI 7B Chat (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 8192,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text'],
      priority: 3,
      enabled: true
    },
    {
      id: 'rakuten/rakutenai-7b-instruct',
      name: 'RakutenAI 7B Instruct (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 8192,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 3,
      enabled: true
    },
    {
      id: 'sarvamai/sarvam-m',
      name: 'Sarvam M (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 8192,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text'],
      priority: 3,
      enabled: true
    },
    {
      id: 'snowflake/arctic-embed-l',
      name: 'Arctic Embed L (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 512,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text'],
      priority: 3,
      enabled: true
    },
    {
      id: 'speakleash/bielik-11b-v2.3-instruct',
      name: 'Bielik 11B v2.3 (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 8192,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 3,
      enabled: true
    },
    {
      id: 'speakleash/bielik-11b-v2.6-instruct',
      name: 'Bielik 11B v2.6 (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 8192,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 3,
      enabled: true
    },
    {
      id: 'stepfun-ai/step-3.5-flash',
      name: 'Step 3.5 Flash (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 2,
      enabled: true
    },
    {
      id: 'stockmark/stockmark-2-100b-instruct',
      name: 'Stockmark 2 100B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text'],
      priority: 2,
      enabled: true
    },
    {
      id: 'thudm/chatglm3-6b',
      name: 'ChatGLM3 6B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 8192,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 3,
      enabled: true
    },
    {
      id: 'tiiuae/falcon3-7b-instruct',
      name: 'Falcon3 7B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 8192,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 3,
      enabled: true
    },
    {
      id: 'tokyotech-llm/llama-3-swallow-70b-instruct-v0.1',
      name: 'Llama 3 Swallow 70B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 8192,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 2,
      enabled: true
    },
    {
      id: 'upstage/solar-10.7b-instruct',
      name: 'Solar 10.7B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 4096,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 3,
      enabled: true
    },
    {
      id: 'utter-project/eurollm-9b-instruct',
      name: 'EuroLLM 9B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 8192,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text'],
      priority: 3,
      enabled: true
    },
    {
      id: 'writer/palmyra-creative-122b',
      name: 'Palmyra Creative 122B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 32768,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text'],
      priority: 2,
      enabled: true
    },
    {
      id: 'writer/palmyra-fin-70b-32k',
      name: 'Palmyra Fin 70B 32K (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 32768,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text'],
      priority: 2,
      enabled: true
    },
    {
      id: 'writer/palmyra-med-70b',
      name: 'Palmyra Med 70B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 8192,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text'],
      priority: 2,
      enabled: true
    },
    {
      id: 'writer/palmyra-med-70b-32k',
      name: 'Palmyra Med 70B 32K (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 32768,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text'],
      priority: 2,
      enabled: true
    },
    {
      id: 'yentinglin/llama-3-taiwan-70b-instruct',
      name: 'Llama 3 Taiwan 70B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 8192,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 2,
      enabled: true
    },
    {
      id: 'z-ai/glm4.7',
      name: 'GLM-4.7 (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 128000,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code', 'reasoning'],
      priority: 1,
      enabled: true
    },
    {
      id: 'zyphra/zamba2-7b-instruct',
      name: 'Zamba2 7B (NVIDIA)',
      provider: 'nvidia',
      contextWindow: 4096,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 3,
      enabled: true
    },
    // iFlow 模型
    {
      id: 'Qwen3-Coder',
      name: 'Qwen3-Coder (iFlow)',
      provider: 'iflow',
      contextWindow: 131072,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 2,
      enabled: true
    },
    // DeepSeek 模型
    {
      id: 'deepseek-chat',
      name: 'DeepSeek V3',
      provider: 'deepseek',
      contextWindow: 65536,
      costPer1KInput: 0.00027,
      costPer1KOutput: 0.0011,
      capabilities: ['text', 'code'],
      priority: 3,
      enabled: true
    },
    {
      id: 'deepseek-reasoner',
      name: 'DeepSeek R1',
      provider: 'deepseek',
      contextWindow: 65536,
      costPer1KInput: 0.00055,
      costPer1KOutput: 0.00219,
      capabilities: ['text', 'code', 'reasoning'],
      priority: 3,
      enabled: true
    },
    // Ollama 本地模型
    {
      id: 'qwen2.5:7b',
      name: 'Qwen2.5 7B (Ollama)',
      provider: 'ollama',
      contextWindow: 32768,
      costPer1KInput: 0,
      costPer1KOutput: 0,
      capabilities: ['text', 'code'],
      priority: 1,
      enabled: true
    }
  ],
  
  routing: {
    defaultModel: 'gpt-4o-mini',
    enableFallback: true,
    cacheEnabled: true,
    rules: [
      {
        name: '长文本处理',
        condition: {
          type: 'input_length',
          value: { min: 50000 }
        },
        targetModels: ['kimi-k2.5'],
        fallbackModels: ['claude-3-5-sonnet-20241022']
      },
      {
        name: '代码生成',
        condition: {
          type: 'task_type',
          value: ['code', 'programming', 'debug', 'review']
        },
        targetModels: ['claude-3-5-sonnet-20241022', 'gpt-4o'],
        fallbackModels: ['gpt-4o-mini']
      },
      {
        name: '数学推理',
        condition: {
          type: 'task_type',
          value: ['math', 'reasoning', 'logic', 'analysis']
        },
        targetModels: ['o1-mini', 'claude-3-5-sonnet-20241022'],
        fallbackModels: ['gpt-4o']
      },
      {
        name: '经济模式',
        condition: {
          type: 'cost_priority',
          value: 'high'
        },
        targetModels: ['gpt-4o-mini', 'claude-3-haiku-20240307'],
        fallbackModels: ['gpt-4o']
      }
    ]
  },

  // 场景优先级配置（用户可自定义）
  scenarioPriorities: [
    {
      scenario: 'code',
      priorityType: 'speed_first',
      modelRanking: ['groq/llama-3.1-8b-instant', 'groq/mixtral-8x7b-32768', 'siliconflow/Qwen/Qwen2.5-7B-Instruct'],
      freeTierWillingness: 0.9,
      description: '代码生成优先使用免费模型（省钱，Groq速度够快）'
    },
    {
      scenario: 'math',
      priorityType: 'capability_first',
      modelRanking: ['groq/mixtral-8x7b-32768', 'siliconflow/Qwen/Qwen2.5-7B-Instruct', 'groq/llama-3.1-8b-instant'],
      freeTierWillingness: 0.8,
      description: '数学推理优先使用免费模型'
    },
    {
      scenario: 'long_context',
      priorityType: 'capability_first',
      modelRanking: ['siliconflow/Qwen/Qwen2.5-7B-Instruct', 'groq/mixtral-8x7b-32768'],
      freeTierWillingness: 0.7,
      description: '长文本优先使用免费模型（Qwen支持128K）'
    },
    {
      scenario: 'creative',
      priorityType: 'expiry_first',
      modelRanking: [],
      freeTierWillingness: 0.5,
      description: '创意写作平衡使用'
    },
    {
      scenario: 'translation',
      priorityType: 'expiry_first',
      modelRanking: [],
      freeTierWillingness: 0.8,
      description: '翻译优先使用免费模型'
    },
    {
      scenario: 'analysis',
      priorityType: 'capability_first',
      modelRanking: ['groq/mixtral-8x7b-32768', 'siliconflow/Qwen2.5-7B-Instruct'],
      freeTierWillingness: 0.6,
      description: '分析任务平衡使用'
    },
    {
      scenario: 'general',
      priorityType: 'expiry_first',
      modelRanking: [],
      freeTierWillingness: 0.3,
      description: '通用对话优先使用付费模型（体验更好）'
    }
  ],

  user: {
    defaultPriority: 'balanced',
    monthlyBudget: 50,
    preferredProviders: ['groq', 'siliconflow', 'openai', 'anthropic', 'moonshot']
  },

  retry: {
    maxAttempts: 3,
    enableRerouting: true,
    exponentialBackoff: true,
    baseDelayMs: 1000,
    maxDelayMs: 10000,
    retryableErrors: [
      'network_error',
      'rate_limit',
      'server_error',
      'quota_exceeded'
    ]
  },

  monitoring: {
    enabled: true,
    logLevel: 'info',
    metricsRetention: 30
  }
};

// 加载用户自定义配置
export function loadConfig(): GatewayConfig {
  // 尝试从 config.json 加载用户自定义配置
  try {
    const configPath = path.join(process.cwd(), 'config.json');

    if (fs.existsSync(configPath)) {
      const userConfig = JSON.parse(fs.readFileSync(configPath, 'utf-8'));

      // 合并用户配置和默认配置
      return {
        ...defaultConfig,
        ...userConfig,
        // 如果用户提供了场景优先级配置，使用用户的配置
        scenarioPriorities: userConfig.scenarioPriorities || defaultConfig.scenarioPriorities
      };
    }
  } catch (error) {
    console.warn('加载用户配置失败，使用默认配置:', error);
  }

  return defaultConfig;
}
